# Generated by Django 5.2.14 on 2026-05-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Текущий пробег (км)')),
                ('drive_style', models.CharField(choices=[('city', 'Город'), ('highway', 'Трасса'), ('mixed', 'Смешанный')], default='mixed', max_length=10, verbose_name='Стиль езды')),
                ('last_to_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('last_to_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег при последнем ТО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('oil', 'Замена масла'), ('oil_filter', 'Масляный фильтр'), ('air_filter', 'Воздушный фильтр'), ('cabin_filter', 'Салонный фильтр'), ('fuel_filter', 'Топливный фильтр'), ('spark_plugs', 'Свечи зажигания'), ('brake_fluid', 'Тормозная жидкость'), ('coolant', 'Охлаждающая жидкость'), ('transmission', 'Трансмиссионное масло'), ('timing_belt', 'Ремень ГРМ'), ('brake_pads', 'Тормозные колодки'), ('tires', 'Шины'), ('battery', 'Аккумулятор'), ('other', 'Другое')], max_length=30, verbose_name='Вид работы')),
                ('date', models.DateField(verbose_name='Дата замены')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег при замене (км)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость (руб.)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='garage.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Запись ТО',
                'verbose_name_plural': 'История ТО',
                'ordering': ['-date'],
            },
        ),
    ]
