# Generated by Django 5.2.14 on 2026-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license_issue',
            field=models.DateField(blank=True, null=True, verbose_name='ВУ (дата выдачи)'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_cert_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Мед. справка (дата выдачи)'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('recovery', 'Сброс пароля'), ('verify', 'Верификация'), ('email_verify', 'Верификация email')], default='recovery', max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='ВУ (до)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cert_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Мед. справка (до)'),
        ),
    ]
