# Generated by Django 5.2.14 on 2026-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_driver_license_issue_user_medical_cert_issue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscode',
            options={'verbose_name': 'SMS-код', 'verbose_name_plural': 'SMS-коды'},
        ),
        migrations.RemoveField(
            model_name='smscode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='smscode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_cost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_cert_cost',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Токен сброса пароля'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('reset', 'Сброс пароля'), ('register', 'Регистрация'), ('email', 'Подтверждение email')], default='reset', max_length=20, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='personal', max_length=20, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок ВУ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_license_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ВУ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, verbose_name='FCM Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cert_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Срок мед. справки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cert_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи мед. справки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
