# Generated by Django 5.2.14 on 2026-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_color',
            field=models.CharField(default='#C4A882', max_length=10, verbose_name='Цвет логотипа (hex)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_text',
            field=models.CharField(blank=True, max_length=10, verbose_name='Текст логотипа'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('service', 'Автосервис'), ('evacuator', 'Эвакуатор'), ('parts', 'Запчасти')], default='service', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_hours',
            field=models.CharField(blank=True, default='Пн–Сб: 9:00–19:00', max_length=100, verbose_name='Режим работы'),
        ),
    ]
