# Generated by Django 5.2.14 on 2026-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_favoriteorganization_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='services_list',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Виды услуг'),
        ),
    ]
