# Generated by Django 5.2.14 on 2026-05-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_services_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteorganization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранная организация', 'verbose_name_plural': 'Избранные организации'},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteorganization',
            unique_together=set(),
        ),
    ]
